apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gitea.name" . }}
    helm.sh/chart: {{ include "gitea.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ default 3000 .Values.config.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.sshPort }}
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: {{ include "gitea.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
